### ISSUE TITLE
advanced functionalities

### ISSUE THREAD

**Issue by Raffaello** [BlueRedSkyLTD/PowerDir#3]
- [x] write few basic tests (#1)
- [x] update help Get-Powerdir (#1)
- [ ] filter by (attributes, size, date)
- [ ] advanced search patterns: eg: dir?\\*.exe (globbing)
- [ ] pipeline the input for eg ` | sort` to sort the results default by `Name` but attribute can be selected.
- [ ] sorting by Name, etc.....
- [ ] pagination
- [ ] update Readme.md
- [x] ~add a better theme for colors / customize themes. (24 bits)~ (#9 #4 )
